// File generated by FlutterFire CLI.
// Configure with your own Firebase project credentials using:
// flutterfire configure
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDemoKeyForPharmAlertWeb',
    appId: '1:498212208289:web:pharmalert123456',
    messagingSenderId: '498212208289',
    projectId: 'pharmalert-lk',
    authDomain: 'pharmalert-lk.firebaseapp.com',
    storageBucket: 'pharmalert-lk.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDemoKeyForPharmAlertAndroid',
    appId: '1:498212208289:android:pharmalert123456',
    messagingSenderId: '498212208289',
    projectId: 'pharmalert-lk',
    storageBucket: 'pharmalert-lk.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDemoKeyForPharmAlertIOS',
    appId: '1:498212208289:ios:pharmalert123456',
    messagingSenderId: '498212208289',
    projectId: 'pharmalert-lk',
    storageBucket: 'pharmalert-lk.appspot.com',
    iosBundleId: 'com.pharmalert.lk',
  );
}
